### ISSUE TITLE
[FIX] 마이페이지 평가 기능

### ISSUE THREAD

**Issue by Minoyam** [Yapp-17th/Android_2_Backend#101]
현재
좋아요를 눌렀을때 true를 보내면 isLike가 true로 바뀝니다.
싫어요를 눌렀을때 false을 보내면 isLike가 false로 바뀝니다.

싫어요를 눌렀을때 false을 보내면 isLike가 false이 되는게 아니라
isDisLike가 true로 돼야합니다.
isDisLike에 대한 변경이 필요합니다.

**Comment by sypark9646** [comment]
이거 지금도

> 싫어요를 눌렀을때 false을 보내면 isLike가 false이 되는게 아니라
isDisLike가 true로 돼야합니다.
isDisLike에 대한 변경이 필요합니다.

확인해 봤는데 이 부분 isDislike true로 변경됨과 동시에 isLike false로 되고 있는데
일단 구조 조금 바꿔서 업데이트 했으니까 확인 한 번만 부탁드립니당
