### ISSUE TITLE
병목현상 보는법, gateway 성능 향상

### ISSUE THREAD

**Issue by sypark9646** [Yapp-17th/Android_2_Backend#186]

**Comment by sypark9646** [comment]
## visualvm - JVM을 실시간으로 모니터링하는 툴
https://visualvm.github.io/
https://blog.naver.com/PostView.nhn?blogId=simpolor&logNo=221311749562

## elk - bottleneck visualize 추가
https://www.elastic.co/guide/en/kibana/6.8/apm-bottlenecks.html

우리 근데 모니터링 지금은 다시 뺐지만 logstash가 느리대여 그래서 fluentd를 대신 쓰나봐욥

https://woowabros.github.io/experience/2018/05/08/billing-performance_test_experience.html

**Comment by sypark9646** [comment]
thread pooling=>Async

게이트웨이에서 캐싱
http://www.svenhartmann.eu/blog/zuul-cache-valid-requests-with-x-zuul-cacheable-header => 못씀

**Comment by sypark9646** [comment]
스레드 서비스 디스커버리 공부해보기~~~

**Comment by dnjscksdn98** [comment]
오 좋은 리서치👍🏻
