### ISSUE TITLE
성능 / 메모리 개선

### ISSUE THREAD

**Issue by dnjscksdn98** [Yapp-17th/Android_2_Backend#191]
- ~primitive type~
- string control -> google guava, apache common
- exception class -> base exception을 만들어서 이를 상속 받기
  - exception handler 크기 줄이기

**Comment by sypark9646** [comment]
https://bitmovin.com/finding-memory-leaks-java-p2/
https://medium.com/@larry.l.fang/jvm-memory-optimisation-in-docker-46cda197295a

https://developers.redhat.com/blog/2017/03/14/java-inside-docker/

**Comment by dnjscksdn98** [comment]
https://medium.com/wix-engineering/how-to-reduce-your-jvm-app-memory-footprint-in-docker-and-kubernetes-d6e030d21298

**Comment by sypark9646** [comment]
~stream 덜 쓸수 있는 부분에선 제거~
~optional도~

**Comment by sypark9646** [comment]
```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 137363456 bytes for committing reserved memory.
# An error report file with more information is saved as:
# //hs_err_pid1.log
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000d1e00000, 137363456, 0) failed; error='Not enough space' (errno=12)
```
./var/lib/docker/overlay2/3c9c558bd956b3b0409a54dc2f69f124dff2b0091fb003b5284a37eac7d5cdd4/merged/hs_err_pid1.log
./var/lib/docker/overlay2/3c9c558bd956b3b0409a54dc2f69f124dff2b0091fb003b5284a37eac7d5cdd4/diff/hs_err_pid1.log
