### ISSUE TITLE
feat: 정지 -> 탈퇴 자동변경

### ISSUE THREAD

**Issue by sypark9646** [Yapp-17th/Android_2_Backend#61]
신고 횟수 기준
* 10 회 -> 일주일 정지(로그인 차단) 및 경고장
* 20회 시, 자동 탈퇴

**Comment by dnjscksdn98** [comment]
- 게시글 신청/승인/거절
  - 정지/차단된 사용자 게시글이면 막기

**Comment by sypark9646** [comment]
watcher에서 integer 필드 신고 날짜 며칠 지났는지
